apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: windsage-webhook
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    windsage:
      port: "12000"
      endpoint: /windsage
      method: POST
